In [1]:
#NumPy Installation in Python
!pip install numpy

In [2]:
#Importing NumPy and printing version number
import numpy as np
print(np.__version__)

1.21.5


In [4]:
#EXERCISE 1 - Element-wise addition of 2 numpy arrays
a = np.array([[1,2,3],
            [4,5,6]])

b = np.array([[10,11,12],
             [13,14,15]])

c = a+b

c

array([[11, 13, 15],
       [17, 19, 21]])

In [5]:
#EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
a = np.array([[1,2,3],
            [4,5,6]])

b = 2*a
print(b)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
#EXERCISE 3 - Identity Matrix
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
#EXERCISE 4 - Array re-dimensioning
#Convert a 1-D array to a 3-D array
a = np.array([x for x in range(27)])
o = a.reshape((3,3,3))
print(o)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [8]:
# EXERCISE 5 - Array datatype conversion
# Convert all the elements of a numpy array from float to integer datatype

a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

[[2 3 1]
 [4 2 1]]


In [9]:
#EXERCISE 6 - Obtaining Boolean Array from Binary Array
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
o = a.astype('bool')
print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


In [10]:
#EXERCISE 7 - Horizontal Stacking of Numpy Arrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
#EXERCISE 8 - Vertically Stacking of Numpy Arrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.vstack((a1, a2))

print(o)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
#EXERCISE 9 - Custom Sequence Generation
#Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

# Or

a = np.arange (0,101,2)
a

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
# EXERCISE 10 - Getting the positions (indexes) where elements of 2 numpy arrays match
# From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
print(np.where(a == b))

(array([0, 3, 4], dtype=int64),)


In [17]:
#EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range
#Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)
o = np.linspace(0,100,5)
o

array([  0.,  25.,  50.,  75., 100.])

In [18]:
#EXERCISE 12 - Matrix Generation with one particular value
#Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5
o = np.full((2,3), 5)
o

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
a = np.ones((2,3))
o = 5*a
print(o)

[[5. 5. 5.]
 [5. 5. 5.]]


In [22]:
# EXERCISE 13 - Array Generation by repeatition of a small array across each dimension
# Output an array by repeating a smaller array of 2 dimensions, 10 times
a = np.array([[1,2,3],
             [4,5,6]])
o = np.tile(a,10)
o

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
        2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4,
        5, 6, 4, 5, 6, 4, 5, 6]])

In [23]:
#EXERCISE 14 - Array Generation of random integers within a specified range
#Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)
np.random.seed(123) # # setting the seed
o = np.random.randint(0, 10, size = (5,5))
o

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3],
       [4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7]])

In [24]:
# EXERCISE 15 - Array Generation of random numbers following normal distribution
# Output a 3-by-3 array of random numbers following normal distribution
np.random.seed(123) # # setting the seed
o = np.random.normal(size = (3,3))
o

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626]])

In [31]:
#EXERCISE 16 - Matrix Multiplication
#Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

b = np.array([[2,3,4],
             [5,6,7],
             [8,9,10]])
o = a@b
print(o,'\n')

#or

c = np.matmul(a,b)
print(c)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]] 

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [32]:
#EXERCISE 17 - Matrix Transpose
#Output the transpose of a matrix (as numpy array)
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
c = a.T
print(c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
#EXERCISE 18 - Sine of an Angle (in radians)
#Calculate the sine of an array of angles (in radians) using NumPy
angles = np.array([3.14, 3.14/2, 6.28])
sine_of_angles = np.sin(angles)
print('Sine of the given array of angles = ', sine_of_angles)

Sineof the given array of angles =  [ 0.00159265  0.99999968 -0.0031853 ]


In [34]:
#EXERCISE 19 - Cosine Similarity
# Calculate the cosine similarity of 2 vectors (as numpy arrays)
angles = np.array([3.14, 3.14/2, 6.28])
cosine_of_angles = np.cos(angles)
print('Cosine of the given array of angles = ', cosine_of_angles)

Cosine of the given array of angles =  [-9.99998732e-01  7.96326711e-04  9.99994927e-01]


In [35]:
#EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order
#Output the array element indexes such that the array elements appear in the ascending order
array = np.array([10,1,5,2])
indexes = np.argsort(array)
print(indexes)

[1 3 2 0]
